### PR TITLE
Update cpp_fmriprep.slurm

### PR DESCRIPTION
**Pull request by marcobarilari**
Do these numbers make sense?

### CODE REVIEW

**Comment by marcobarilari** [comment]
They seem to the resources limit for lemaitre3 (deducted from https://www.ceci-hpc.be/scriptgen.html) and `# SBATCH --ntasks-per-node=2` from Filippo tests does not seems to make any difference

**Comment by yyang1234** [comment]
Hi, for me my problem isn't related to memory but I tried to run with these numbers and they works. So they make sense.

**Comment by marcobarilari** [comment]
If with these numbers you were able to run to the end without error the problematic subjects THEN (1) it is very good news and (2) very likely that your problem `could not find file X` was related to memory.

Possible explanation In a nutshell: we provided too little "ram" memory so that fmriprep was forced to free it up during some processes, therefore it deleted cached files that were supposed to be used later and not being there it dumbly through the error you saw.

LMK if it makes sense to you

**Comment by yyang1234** [comment]
Hi, what you said is an important point. But the error that happened to me appeared even with these new numbers. The error was solved by clearing the content in both the output folder and the scratch folder. 
Now in the slurm file I define workdir like this `--work-dir /scratch_dir/work-fmriprep/"${subjID}" \` instead of  `--work-dir /scratch_dir/work-fmriprep \`  to make the scratch folder less likely to be mixed with each others. Does it make sense?

**Comment by yyang1234** [comment]
I also found that for instance, a single subject has three tasks, running the first task works without any issues. However, when I subsequently run the second task for the same subject, an error occurs. Now I run all tasks for one subject at one time to avoid the issue.

**Comment by marcobarilari** [comment]
Ah interesting, well this could be important to change as well in this repo. Will run some trials.

**Comment by marcobarilari** [comment]
> I also found that for instance, a single subject has three tasks, running the first task works without any issues. However, when I subsequently run the second task for the same subject, an error occurs. Now I run all tasks for one subject at one time to avoid the issue.

What was the error? Let's share it in the trouble shooting section in his repo

**Comment by yyang1234** [comment]
The same error as I posted before. I think the error related to recycled either the output folder or the scratch folder within same participants.

**Pull request merged**
